export const MAX_CHARACTERS_IN_TOKEN = 128
export const MAX_CHARACTERS_IN_USER_ID = 32
export const MAX_CHARACTERS_IN_USER_NAME = 32
export const MAX_CHARACTERS_IN_USER_TAG = 32
export const MAX_CHARACTERS_IN_USER_PASSWORD = 32
export const MAX_CHARACTERS_IN_PERMISSION = 32
export const MAX_CHARACTERS_IN_CONTAINER_ID = 32